#!/bin/sh

# scripts/bootstrap: Creates conichi directory.
#                    Clones all conichi ios projects.

set -e

green=`tput setaf 2`
reset=`tput sgr0`

cd $($HOME)

echo "${green}===== Creating conichi directory for all ios projects… =====${reset}"
mkdir conichi

echo "${green}===== Moving into conichi directory… =====${reset}"
cd conichi

### ios-guest setup

echo "${green}===== Cloning ios-guest repo… =====${reset}"
git clone git@github.com:conichiGMBH/ios-guest.git

### ios-merchant setup

echo "${green}===== Cloning ios-merchant repo… =====${reset}"
git clone git@github.com:conichiGMBH/ios-merchant.git

### ios-beacon-tool setup

echo "${green}===== Cloning ios-beacon-tool repo… =====${reset}"
git clone git@github.com:conichiGMBH/ios-beacon-tool.git ios-beacon-tool

### ios-sdk setup

echo "${green}===== Cloning ios-sdk repo… =====${reset}"
git clone git@github.com:conichiGMBH/ios-sdk.git

echo "${green}===== Bootstrap ios-sdk… =====${reset}"
cd ios-sdk
fastlane bootstrap
cd $($HOME/conichi)

### ios-utilities setup

echo "${green}===== Cloning ios-utilities repo… =====${reset}"
git clone git@github.com:conichiGMBH/ios-utilities.git
cd ios-utilities
fastlane bootstrap
cd $($HOME/conichi)
